# Generated by Django 5.2.1 on 2025-06-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jawanndenn", "0003_poll_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="yes",
            field=models.BooleanField(null=True),
        ),
    ]
