# Generated by Django 5.2.2 on 2025-08-04 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jawanndenn", "0004_tribool_votes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="equal_width",
        ),
    ]
